### ISSUE TITLE
Property "_temperature" is not a valid property

### ISSUE THREAD

**Issue by matthiasmwolf** [andig/pimatic-fritz#40] opened 2017-04-12 12:49 UTC
The plugin seems to set an invalid config property with value NULL.

![image](https://cloud.githubusercontent.com/assets/8525013/24957987/03f6d83c-1f8e-11e7-855e-460a37b6b7f6.png)

After deleting the property manually using nano over ssh on pimatics' `config.json` it is reset after restart.

It doesn't seem to provoke any misbehaviour, though.

**Comment by andig** [comment] 2017-04-12 13:02
Duplicate of https://github.com/andig/pimatic-fritz/issues/39

**Closed as completed by andig** 2017-04-12 13:02 UTC
Labels: duplicate
